package com.rally.gateway.filter;

import com.rally.gateway.config.GatewayProperties;
import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.SpanContext;
import io.opentelemetry.api.trace.propagation.W3CTraceContextPropagator;
import io.opentelemetry.context.Context;
import org.springframework.cloud.gateway.filter.GatewayFilterChain;
import org.springframework.cloud.gateway.filter.GlobalFilter;
import org.springframework.core.Ordered;
import org.springframework.http.HttpHeaders;
import org.springframework.stereotype.Component;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

import java.security.SecureRandom;
import java.util.HashMap;
import java.util.HexFormat;
import java.util.Map;
import java.util.regex.Pattern;

/**
 * Guarantees every proxied request carries a valid Gateway-owned W3C {@code traceparent}
 * for downstream services — ignoring any untrusted client-supplied tracing headers:
 *
 * <ul>
 *   <li>Always overrides incoming {@code traceparent} and strips untrusted {@code tracestate}.</li>
 *   <li>Injects the current OpenTelemetry server span context generated by Gateway instrumentation.</li>
 *   <li>If no valid span context is in scope, generates a fresh sampled {@code 00-<trace>-<span>-01} header.</li>
 *   <li>Re-emits Gateway's {@code X-Correlation-Id} as W3C {@code baggage} so it lands in downstream MDC/Loki/Jaeger tags.</li>
 * </ul>
 *
 * <p>Runs right after {@link RequestIdGlobalFilter} so the correlation id it publishes
 * as baggage is already the gateway-owned value.
 */
@Component
public class TracePropagationGlobalFilter implements GlobalFilter, Ordered {

    static final String TRACESTATE_HEADER = "tracestate";
    static final String BAGGAGE_HEADER = "baggage";

    private static final Pattern VALID_TRACEPARENT = Pattern.compile(
            "^(?!ff)[0-9a-f]{2}-(?!0{32})[0-9a-f]{32}-(?!0{16})[0-9a-f]{16}-[0-9a-f]{2}$");

    private static final SecureRandom RANDOM = new SecureRandom();
    private static final HexFormat HEX = HexFormat.of();

    private final GatewayProperties properties;

    public TracePropagationGlobalFilter(GatewayProperties properties) {
        this.properties = properties;
    }

    @Override
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        // 1. Extract Correlation ID generated by Gateway's RequestIdGlobalFilter
        String correlationId = exchange.getRequest().getHeaders()
                .getFirst(properties.getRequestIdHeader());

        // 2. Resolve Gateway traceparent (from active OTel context or generated fallback)
        String traceparent = injectCurrentContext();
        if (traceparent == null) {
            traceparent = "00-" + randomHex(16) + "-" + randomHex(8) + "-01";
        }

        String outgoingTraceparent = traceparent;

        // 3. Mutate request: override traceparent, remove external tracestate, attach correlation baggage
        ServerWebExchange traced = exchange.mutate()
                .request(request -> request.headers(headers -> {
                    headers.set(properties.getTraceparentHeader(), outgoingTraceparent);
                    headers.remove(TRACESTATE_HEADER); // Always drop untrusted incoming tracestate
                    publishCorrelationAsBaggage(headers, correlationId);
                }))
                .build();

        // Echo the gateway-owned traceparent back (Angular network tab). beforeCommit
        // covers proxied, composed/short-circuited, and error responses alike.
        traced.getResponse().beforeCommit(() -> {
            traced.getResponse().getHeaders().set(properties.getTraceparentHeader(), outgoingTraceparent);
            return Mono.empty();
        });

        // 4. Publish the gateway-owned ids to the Reactor context so the central
        // WebClient ExchangeFilterFunction can stamp every composition side-call.
        // Nulls are not allowed in a Context, so only present values are published.
        // (reactor.util.context.Context is fully qualified: Context here means the OTel one.)
        reactor.util.context.Context propagationContext = reactor.util.context.Context.empty();
        if (correlationId != null && !correlationId.isBlank()) {
            propagationContext = propagationContext.put(properties.getRequestIdHeader(), correlationId);
        }
        propagationContext = propagationContext.put(properties.getTraceparentHeader(), outgoingTraceparent);

        return chain.filter(traced).contextWrite(propagationContext);
    }

    /** Injects the in-scope OTel span context, or {@code null} when none is valid. */
    private static String injectCurrentContext() {
        SpanContext spanContext = Span.current().getSpanContext();
        if (!spanContext.isValid()) {
            return null;
        }
        Map<String, String> carrier = new HashMap<>(2);
        W3CTraceContextPropagator.getInstance()
                .inject(Context.current(), carrier, Map::put);
        // OTel always propagates under the standard key; the property defaults to it.
        String traceparent = carrier.get("traceparent");
        return traceparent != null && VALID_TRACEPARENT.matcher(traceparent).matches()
                ? traceparent
                : null;
    }

    private static String randomHex(int bytes) {
        byte[] value = new byte[bytes];
        RANDOM.nextBytes(value);
        return HEX.formatHex(value);
    }

    private void publishCorrelationAsBaggage(HttpHeaders headers, String correlationId) {
        if (correlationId == null || correlationId.isBlank()) {
            return;
        }
        String entry = properties.getRequestIdHeader() + "=" + correlationId.trim();
        String baggage = headers.getFirst(BAGGAGE_HEADER);
        if (baggage == null || baggage.isBlank()) {
            headers.set(BAGGAGE_HEADER, entry);
        } else if (!baggage.contains(entry)) {
            headers.set(BAGGAGE_HEADER, baggage + "," + entry);
        }
    }

    @Override
    public int getOrder() {
        return Ordered.HIGHEST_PRECEDENCE + 1;
    }
}